[[redirects]]
  from = "https://customercareservice.co/admin*"
  to = "/admin"
  status = 301
  force = true

[[redirects]]
  from = "/sony-tv-repair"
  to = "/sony-tv-repair"
  status = 301
  force = true
